//! Push delivery (Web Push and FCM) for mention/reply/all-messages
//! notifications.
//!
//! When the tap pipeline indexes a notification it hands it here; we fan a
//! push out to every subscription the recipient has registered, whatever
//! provider each one uses, so the notification arrives even when the app is
//! fully closed. Delivery is filtered to match the in-app rules:
//!
//! - **Level** — `message`-kind rows (every message, for recipients on the
//!   `"all"` notification level) are only ever generated by
//!   `notifications::index_message_notifications` for members who haven't
//!   opted down to mentions/replies-only and haven't muted the channel, so no
//!   extra level check is needed here.
//! - **Mutes** — skipped if the recipient muted the channel or its community
//!   (belt-and-braces for `mention`/`reply` rows, which aren't pre-filtered
//!   by mute state the way `message` rows are).
//! - **Do Not Disturb** — skipped while the recipient's state is `dnd`.
//!
//! Web Push: the `web-push` crate builds and encrypts the message (RFC 8291
//! aes128gcm) and signs the VAPID JWT; we send the resulting request with the
//! existing `reqwest` client rather than pulling in a second HTTP/TLS stack.
//! The endpoint is caller-supplied at registration time, so it's routed
//! through `embed_fetch`'s SSRF guard.
//!
//! FCM: delivery goes through `fcm_send`'s HTTP v1 client. The registration
//! token isn't a URL, so the SSRF guard doesn't apply — the target host is
//! fixed and trusted instead.

use std::collections::HashMap;

use sea_orm::DatabaseConnection;
use serde::Serialize;
use web_push::{ContentEncoding, SubscriptionInfo, VapidSignatureBuilder, WebPushMessageBuilder};

use crate::lib::at_uri::AtUri;
use crate::lib::fcm_config::fcm_config;
use crate::lib::fcm_send::{self, SendOutcome};
use crate::lib::get_state::get_state;
use crate::lib::notifications::IndexedNotification;
use crate::lib::push_subscriptions;
use crate::lib::vapid_config::vapid_config;
use crate::models::record_data;
use crate::xrpc::social::colibri::actor::list_mutes_handler::fetch_mutes;
use crate::xrpc::social::colibri::actor::set_state_handler::UserState;

const COMMUNITY_NSID: &str = "social.colibri.community";
const FACET_SPOILER_TYPE: &str = "social.colibri.richtext.facet#spoiler";

/// Replaces every spoiler-covered range of `text` with a placeholder so hidden
/// content never appears in a push preview
fn redact_spoilers(text: &str, facets: &[serde_json::Value]) -> String {
    let mut ranges: Vec<(usize, usize)> = Vec::new();
    for facet in facets {
        let is_spoiler = facet
            .get("features")
            .and_then(|f| f.as_array())
            .is_some_and(|features| {
                features.iter().any(|feature| {
                    feature.get("$type").and_then(|t| t.as_str()) == Some(FACET_SPOILER_TYPE)
                })
            });
        if !is_spoiler {
            continue;
        }
        let index = facet.get("index");
        let start = index
            .and_then(|i| i.get("byteStart"))
            .and_then(serde_json::Value::as_u64);
        let end = index
            .and_then(|i| i.get("byteEnd"))
            .and_then(serde_json::Value::as_u64);
        let (Some(start), Some(end)) = (start, end) else {
            continue;
        };
        let (start, end) = (start as usize, end as usize);
        if start < end
            && end <= text.len()
            && text.is_char_boundary(start)
            && text.is_char_boundary(end)
        {
            ranges.push((start, end));
        }
    }
    if ranges.is_empty() {
        return text.to_string();
    }
    ranges.sort_by_key(|&(start, _)| start);

    let mut out = String::with_capacity(text.len());
    let mut cursor = 0usize;
    for (start, end) in ranges {
        // Skip ranges that overlap one already redacted (nested/duplicate)
        if start < cursor {
            continue;
        }
        out.push_str(&text[cursor..start]);
        out.push_str("█████");
        cursor = end;
    }
    out.push_str(&text[cursor..]);
    out
}

/// Routing hints the Service Worker uses on click.
#[derive(Serialize)]
struct PushData {
    #[serde(rename = "channelUri")]
    channel_uri: String,
    #[serde(rename = "messageUri")]
    message_uri: String,
}

/// JSON push payload, shaped for `push-sw.js`.
#[derive(Serialize)]
struct PushPayload {
    title: String,
    body: String,
    tag: String,
    data: PushData,
}

/// Whether `channel_uri` is muted by the given mute records. Mirrors the
/// client's `Mutes` logic: a mute matches when its subject is the channel
/// itself, or is the community (same authority DID) that owns the channel —
/// a community mute suppresses all of its channels.
pub fn is_muted(mutes: &[record_data::Model], channel_uri: &str) -> bool {
    let channel_authority = AtUri::parse(channel_uri).map(|u| u.authority);
    for mute in mutes {
        let Some(subject) = mute.data.get("subject").and_then(|s| s.as_str()) else {
            continue;
        };
        if subject == channel_uri {
            return true;
        }
        if let Some(parsed) = AtUri::parse(subject)
            && parsed.collection == COMMUNITY_NSID
            && channel_authority.as_deref() == Some(parsed.authority.as_str())
        {
            return true;
        }
    }
    false
}

/// Whether the notification passes the DND + mute filters and should be
/// delivered at all, independent of provider. Fails open on a read error — a
/// missing state/mutes row shouldn't silently drop notifications.
async fn passes_delivery_filters(
    db: &DatabaseConnection,
    recipient_did: &str,
    channel_uri: &str,
) -> bool {
    match get_state(recipient_did.to_string(), db).await {
        Ok(UserState::Dnd) => return false,
        Ok(_) => {}
        Err(e) => {
            log::warn!("push: failed to read state for {recipient_did}: {e}");
        }
    }

    match fetch_mutes(db, recipient_did).await {
        Ok(mutes) if is_muted(&mutes, channel_uri) => return false,
        Ok(_) => {}
        Err(e) => {
            log::warn!("push: failed to read mutes for {recipient_did}: {e}");
        }
    }

    true
}

/// The notification title for a given kind (+ role name, for role mentions).
fn notification_title(kind: &str, mention_role_name: Option<&str>) -> String {
    match kind {
        "reply" => String::from("New reply"),
        "message" => String::from("New message"),
        _ => match mention_role_name {
            Some(role) => format!("Mentioned via @{role}"),
            None => String::from("New mention"),
        },
    }
}

/// Builds the provider-agnostic payload both `send_web_one` and
/// `send_fcm_one` deliver.
fn build_payload(notification: &IndexedNotification) -> PushPayload {
    PushPayload {
        title: notification_title(
            &notification.row.kind,
            notification.row.mention_role_name.as_deref(),
        ),
        body: redact_spoilers(&notification.message.text, &notification.message.facets),
        tag: notification.row.message_uri.clone(),
        data: PushData {
            channel_uri: notification.row.channel_uri.clone(),
            message_uri: notification.row.message_uri.clone(),
        },
    }
}

/// Applies the DND + mute filters and, if the notification passes, delivers a
/// push to each of the recipient's subscriptions, dispatched per-provider.
/// Best-effort: every error is logged and swallowed so a failed push never
/// disrupts the tap pipeline. Intended to be `tokio::spawn`ed from the tap
/// loop.
pub async fn deliver(db: DatabaseConnection, notification: IndexedNotification) {
    let recipient_did = notification.row.recipient_did.clone();
    let channel_uri = notification.row.channel_uri.clone();

    if !passes_delivery_filters(&db, &recipient_did, &channel_uri).await {
        return;
    }

    let payload = build_payload(&notification);

    let subscriptions = match push_subscriptions::list_for_actor(&db, &recipient_did).await {
        Ok(subs) => subs,
        Err(e) => {
            log::warn!("push: failed to list subscriptions for {recipient_did}: {e}");
            return;
        }
    };

    for sub in subscriptions {
        let result = match sub.provider.as_str() {
            "web" => send_web_one(&db, &sub, &payload).await,
            "fcm" => send_fcm_one(&db, &sub, &payload).await,
            other => {
                log::warn!(
                    "push: unknown provider '{other}' for subscription {}",
                    sub.id
                );
                continue;
            }
        };
        if let Err(e) = result {
            log::warn!("push: delivery to subscription {} failed: {e}", sub.id);
        }
    }
}

/// Builds the encrypted/signed request for a single Web Push subscription and
/// sends it. On a `404`/`410` from the push service the subscription is
/// pruned. The outbound request is validated and pinned the same way
/// `embed_fetch` guards other outbound fetches — the endpoint is
/// caller-supplied at registration time, so it's treated as untrusted here
/// too. No-ops (returns `Ok`) if VAPID isn't configured.
async fn send_web_one(
    db: &DatabaseConnection,
    sub: &crate::models::push_subscriptions::Model,
    payload: &PushPayload,
) -> Result<(), String> {
    let Some(config) = vapid_config() else {
        return Ok(());
    };

    let (p256dh, auth) = match (sub.p256dh.as_deref(), sub.auth.as_deref()) {
        (Some(p256dh), Some(auth)) => (p256dh, auth),
        _ => return Err(String::from("web push subscription missing p256dh/auth")),
    };

    let body = serde_json::to_vec(payload).map_err(|e| format!("serialize payload: {e}"))?;

    let subscription_info =
        SubscriptionInfo::new(sub.endpoint.clone(), p256dh.to_string(), auth.to_string());

    let mut sig_builder =
        VapidSignatureBuilder::from_base64(&config.private_key, &subscription_info)
            .map_err(|e| format!("vapid signature: {e}"))?;
    sig_builder.add_claim("sub", config.subject.clone());
    let signature = sig_builder
        .build()
        .map_err(|e| format!("vapid build: {e}"))?;

    let mut builder = WebPushMessageBuilder::new(&subscription_info);
    builder.set_payload(ContentEncoding::Aes128Gcm, &body);
    builder.set_vapid_signature(signature);
    let message = builder.build().map_err(|e| format!("message build: {e}"))?;

    let message_payload = message.payload.ok_or("web push message had no payload")?;

    let content_encoding = match message_payload.content_encoding {
        ContentEncoding::Aes128Gcm => "aes128gcm",
        ContentEncoding::AesGcm => "aesgcm",
    };

    let (client, url) = crate::lib::embed_fetch::guarded_client_for(&message.endpoint.to_string())
        .await
        .map_err(|e| format!("endpoint validation: {e}"))?;

    let mut req = client
        .post(url)
        .header("TTL", message.ttl.to_string())
        .header("Content-Encoding", content_encoding);
    for (name, value) in &message_payload.crypto_headers {
        req = req.header(*name, value);
    }

    let res = req
        .body(message_payload.content)
        .send()
        .await
        .map_err(|e| format!("request: {e}"))?;

    let status = res.status();
    if status == reqwest::StatusCode::NOT_FOUND || status == reqwest::StatusCode::GONE {
        // The push service says this endpoint is dead — drop it so we stop
        // trying.
        let _ = push_subscriptions::delete_by_endpoint(db, "web", &sub.endpoint).await;
    } else if !status.is_success() {
        return Err(format!("push service returned {status}"));
    }

    Ok(())
}

/// Sends a single FCM message. Prunes the subscription when FCM reports the
/// registration token is permanently dead. No-ops (returns `Ok`) if FCM isn't
/// configured.
async fn send_fcm_one(
    db: &DatabaseConnection,
    sub: &crate::models::push_subscriptions::Model,
    payload: &PushPayload,
) -> Result<(), String> {
    let Some(config) = fcm_config() else {
        return Ok(());
    };

    let client = fcm_send::client();
    let access_token = client.access_token(config).await?;

    let mut data = HashMap::new();
    data.insert("channelUri", payload.data.channel_uri.as_str());
    data.insert("messageUri", payload.data.message_uri.as_str());
    data.insert("tag", payload.tag.as_str());

    match client
        .send(
            config,
            &access_token,
            &sub.endpoint,
            &payload.title,
            &payload.body,
            &data,
        )
        .await
    {
        SendOutcome::Delivered => Ok(()),
        SendOutcome::Unregistered => {
            let _ = push_subscriptions::delete_by_endpoint(db, "fcm", &sub.endpoint).await;
            Ok(())
        }
        SendOutcome::Failed(e) => Err(e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lib::notifications::NotificationMessage;
    use crate::models::notifications;
    use rocket::tokio;
    use sea_orm::{DatabaseBackend, MockDatabase};
    use serde_json::json;

    #[test]
    fn notification_title_for_reply() {
        assert_eq!(notification_title("reply", None), "New reply");
    }

    #[test]
    fn notification_title_for_message() {
        assert_eq!(notification_title("message", None), "New message");
    }

    #[test]
    fn notification_title_for_direct_mention() {
        assert_eq!(notification_title("mention", None), "New mention");
    }

    #[test]
    fn notification_title_for_role_mention() {
        assert_eq!(
            notification_title("mention", Some("moderators")),
            "Mentioned via @moderators"
        );
    }

    fn indexed_notification(kind: &str, mention_role_name: Option<&str>) -> IndexedNotification {
        IndexedNotification {
            row: notifications::Model {
                id: 1,
                recipient_did: String::from("did:plc:recipient"),
                kind: String::from(kind),
                message_uri: String::from(
                    "at://did:plc:community/social.colibri.channel.message/msg1",
                ),
                author_did: String::from("did:plc:author"),
                channel_uri: String::from(
                    "at://did:plc:community/social.colibri.channel.text/general",
                ),
                indexed_at: String::from("2026-06-25T00:00:00.000Z"),
                seen_at: None,
                mention_role_name: mention_role_name.map(String::from),
            },
            message: NotificationMessage {
                text: String::from("hello there"),
                facets: Vec::new(),
                created_at: String::from("2026-06-25T00:00:00.000Z"),
                parent: None,
                attachments: Vec::new(),
                edited: None,
            },
        }
    }

    #[test]
    fn build_payload_uses_kind_derived_title_and_routing_data() {
        let payload = build_payload(&indexed_notification("message", None));
        assert_eq!(payload.title, "New message");
        assert_eq!(payload.body, "hello there");
        assert_eq!(
            payload.data.channel_uri,
            "at://did:plc:community/social.colibri.channel.text/general"
        );
        assert_eq!(
            payload.data.message_uri,
            "at://did:plc:community/social.colibri.channel.message/msg1"
        );
    }

    #[tokio::test]
    async fn passes_delivery_filters_true_by_default() {
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results([Vec::<crate::models::user_states::Model>::new()])
            .append_query_results([Vec::<record_data::Model>::new()])
            .into_connection();

        assert!(passes_delivery_filters(&db, "did:plc:recipient", CHANNEL).await);
    }

    #[tokio::test]
    async fn passes_delivery_filters_false_when_dnd() {
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results([vec![crate::models::user_states::Model {
                did: String::from("did:plc:recipient"),
                state: String::from("dnd"),
                channel: None,
                vc: None,
                vc_community: None,
                vc_muted: None,
                vc_deafened: None,
            }]])
            .into_connection();

        assert!(!passes_delivery_filters(&db, "did:plc:recipient", CHANNEL).await);
    }

    #[tokio::test]
    async fn passes_delivery_filters_false_when_channel_muted() {
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results([Vec::<crate::models::user_states::Model>::new()])
            .append_query_results([vec![mute(CHANNEL)]])
            .into_connection();

        assert!(!passes_delivery_filters(&db, "did:plc:recipient", CHANNEL).await);
    }

    #[tokio::test]
    async fn deliver_skips_unknown_provider_without_panicking() {
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results([Vec::<crate::models::user_states::Model>::new()])
            .append_query_results([Vec::<record_data::Model>::new()])
            .append_query_results([vec![crate::models::push_subscriptions::Model {
                id: 1,
                actor_did: String::from("did:plc:recipient"),
                endpoint: String::from("opaque-token"),
                p256dh: None,
                auth: None,
                platform: String::from("android"),
                provider: String::from("carrier-pigeon"),
                created_at: String::from("2026-06-25T00:00:00.000Z"),
            }]])
            .into_connection();

        // Should return without panicking on the unrecognized provider — the
        // dispatch loop logs and skips it.
        deliver(db, indexed_notification("message", None)).await;
    }

    fn mute(subject: &str) -> record_data::Model {
        record_data::Model {
            id: 1,
            did: String::from("did:plc:me"),
            nsid: String::from("social.colibri.actor.mute"),
            rkey: String::from("r"),
            data: json!({ "subject": subject }),
            indexed_at: String::from("2026-06-25T00:00:00.000Z"),
        }
    }

    const CHANNEL: &str = "at://did:plc:community/social.colibri.channel.text/general";

    #[test]
    fn channel_mute_matches_exact_channel() {
        assert!(is_muted(&[mute(CHANNEL)], CHANNEL));
    }

    #[test]
    fn community_mute_matches_any_channel_in_it() {
        let community = "at://did:plc:community/social.colibri.community/self";
        assert!(is_muted(&[mute(community)], CHANNEL));
    }

    #[test]
    fn unrelated_mute_does_not_match() {
        let other = "at://did:plc:other/social.colibri.community/self";
        assert!(!is_muted(&[mute(other)], CHANNEL));
        let other_channel = "at://did:plc:community/social.colibri.channel.text/random";
        assert!(!is_muted(&[mute(other_channel)], CHANNEL));
    }

    #[test]
    fn empty_mutes_never_match() {
        assert!(!is_muted(&[], CHANNEL));
    }

    fn spoiler(byte_start: u64, byte_end: u64) -> serde_json::Value {
        json!({
            "index": { "byteStart": byte_start, "byteEnd": byte_end },
            "features": [{ "$type": FACET_SPOILER_TYPE }],
        })
    }

    #[test]
    fn redacts_spoiler_range() {
        // "psst secret bye" — spoiler covers "secret" at bytes [5, 11).
        assert_eq!(
            redact_spoilers("psst secret bye", &[spoiler(5, 11)]),
            "psst █████ bye"
        );
    }

    #[test]
    fn leaves_text_without_spoilers_untouched() {
        let facets = vec![json!({
            "index": { "byteStart": 0, "byteEnd": 4 },
            "features": [{ "$type": "social.colibri.richtext.facet#bold" }],
        })];
        assert_eq!(redact_spoilers("bold text", &facets), "bold text");
        assert_eq!(redact_spoilers("plain", &[]), "plain");
    }

    #[test]
    fn redacts_multiple_and_respects_char_boundaries() {
        // "café x y" — "café " is 6 bytes (é is 2); spoiler over "x" [6,7) and
        // "y" [8,9).
        assert_eq!(
            redact_spoilers("café x y", &[spoiler(6, 7), spoiler(8, 9)]),
            "café █████ █████"
        );
    }

    #[test]
    fn ignores_out_of_bounds_or_misaligned_ranges() {
        // é spans bytes [3,5); a range ending at 4 is mid-char → left as-is.
        assert_eq!(redact_spoilers("café", &[spoiler(3, 4)]), "café");
        assert_eq!(redact_spoilers("hi", &[spoiler(0, 99)]), "hi");
    }
}
