services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: colibri
      POSTGRES_DB: colibri
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-colibri}",
        ]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - internal

  tap:
    image: ghcr.io/bluesky-social/indigo/tap:latest
    restart: unless-stopped
    environment:
      TAP_WORKERS: ${TAP_WORKERS:-12}
      DATABASE_MAX_CONNECTIONS: ${DATABASE_MAX_CONNECTIONS:-24}
      TAP_ADMIN_PASSWORD: ${TAP_ADMIN_PASSWORD}
      TAP_DATABASE_URL: postgres://root:colibri@postgres:5432/colibri
      TAP_SIGNAL_COLLECTION: social.colibri.actor.data
      TAP_COLLECTION_FILTERS: social.colibri.*,app.bsky.actor.profile
      # TAP_RELAY_URL: https://relay1.eurosky.network
    ports:
      - "2480:2480"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    # volumes:
    #   - tap:./data

volumes:
  postgres:
    driver: local

networks:
  internal:
    driver: bridge
