services:
  app:
    image: ghcr.io/colibri-social/appview:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
    ports:
      - "${SFU_RTC_MIN_PORT:-40000}-${SFU_RTC_MAX_PORT:-40100}:${SFU_RTC_MIN_PORT:-40000}-${SFU_RTC_MAX_PORT:-40100}/udp"
      - "${SFU_RTC_MIN_PORT:-40000}-${SFU_RTC_MAX_PORT:-40100}:${SFU_RTC_MIN_PORT:-40000}-${SFU_RTC_MAX_PORT:-40100}/tcp"
    depends_on:
      postgres:
        condition: service_healthy
      tap:
        condition: service_started
    networks:
      - internal
      - dokploy-network

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-colibri}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-colibri}
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-colibri} -d ${POSTGRES_DB:-colibri}",
        ]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - internal

  tap:
    image: ghcr.io/bluesky-social/indigo/tap:latest
    restart: unless-stopped
    environment:
      TAP_ADMIN_PASSWORD: ${TAP_ADMIN_PASSWORD}
      TAP_DATABASE_URL: ${DATABASE_URL}
      TAP_SIGNAL_COLLECTION: social.colibri.actor.data
      TAP_COLLECTION_FILTERS: social.colibri.*,app.bsky.actor.profile
      TAP_RELAY_URL: https://relay1.us-east.bsky.network
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    volumes:
      - tap:/data

volumes:
  postgres:
    driver: local
  tap:

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true
