//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "author_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub did: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub emoji: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub banner_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub handle: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preferred_state: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
