//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "backfill_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub did: String,
    pub completed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub cursor: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub collection: String,
}

impl ActiveModelBehavior for ActiveModel {}
