//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub uri: String,
    #[sea_orm(column_type = "Text")]
    pub owner_did: String,
    #[sea_orm(column_type = "Text")]
    pub rkey: String,
    #[sea_orm(column_type = "Text")]
    pub community_uri: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub channel_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub category_rkey: Option<String>,
    pub indexed_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
