//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "community_members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub community_uri: String,
    #[sea_orm(column_type = "Text")]
    pub member_did: String,
    #[sea_orm(column_type = "Text")]
    pub membership_rkey: String,
    #[sea_orm(column_type = "Text", unique)]
    pub membership_uri: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub approval_rkey: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub approval_uri: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
