//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "messages_author_rkey_unique")]
    pub rkey: String,
    #[sea_orm(column_type = "Text", unique_key = "messages_author_rkey_unique")]
    pub author_did: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub channel: String,
    pub created_at: DateTimeWithTimeZone,
    pub indexed_at: DateTimeWithTimeZone,
    pub edited: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub facets: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub attachments: Option<Json>,
    pub blocked: bool,
}

impl ActiveModelBehavior for ActiveModel {}
