//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pending_approvals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub approval_uri: String,
    #[sea_orm(column_type = "Text")]
    pub membership_uri: String,
    #[sea_orm(column_type = "Text")]
    pub approval_rkey: String,
}

impl ActiveModelBehavior for ActiveModel {}
