//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(unused)]
pub use super::collection_cursors::Entity as CollectionCursors;
pub use super::firehose_cursors::Entity as FirehoseCursors;
pub use super::list_repos_cursors::Entity as ListReposCursors;
pub use super::outbox_buffers::Entity as OutboxBuffers;
pub use super::repo_records::Entity as RepoRecords;
pub use super::repos::Entity as Repos;
pub use super::resync_buffers::Entity as ResyncBuffers;
