//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "reactions_author_rkey_unique")]
    pub rkey: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reactions_author_target_emoji_unique"
    )]
    pub author_did: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reactions_author_target_emoji_unique"
    )]
    pub emoji: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reactions_author_target_emoji_unique"
    )]
    pub target_rkey: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
