//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "repo_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub did: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub collection: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub rkey: String,
    #[sea_orm(column_type = "Text")]
    pub cid: String,
}

impl ActiveModelBehavior for ActiveModel {}
