//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "repos")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub did: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub handle: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rev: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prev_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_msg: Option<String>,
    pub retry_count: i64,
    pub retry_after: i64,
}

impl ActiveModelBehavior for ActiveModel {}
