//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "user_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub did: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub vc: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub vc_community: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub channel: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
