name: Rust CI

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    if: ${{ !startsWith(github.head_ref, 'release-plz-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust 1.96
        run: rustup toolchain install 1.96 --profile minimal --component rustfmt
      - name: Check formatting
        run: cargo fmt --all --check

  lint:
    name: Lint
    if: ${{ !startsWith(github.head_ref, 'release-plz-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust 1.96
        run: rustup toolchain install 1.96 --profile minimal --component clippy
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
      - name: Run linter
        run: cargo clippy -- -D warnings

  test:
    name: Test
    if: ${{ !startsWith(github.head_ref, 'release-plz-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust 1.96
        run: rustup toolchain install 1.96 --profile minimal
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --all-features
